### ISSUE TITLE
How do I use steemconnect2 in react Native ?

### ISSUE THREAD

**Issue by landlove** [steemit/steemconnect#157]
How do I use steemconnect2 in react Native ? 

Is it possible? Please let me know if you have any suggestions.

**Comment by gregory-latinier** [comment]
Hello,
You can see how it was used in busy.org
https://github.com/busyorg/busy

Look at this file
https://github.com/busyorg/busy/blob/012930e493d3a602651fca3a5a6c19caa6881d20/src/client/steemConnectAPI.js

Or any occurrences to it:
https://github.com/busyorg/busy/search?utf8=%E2%9C%93&q=steemConnectAPI&type=

**Comment by bonustrack** [comment]
Yes it's possible we ever tried, it work the same as doing it on React.js as @gregory-latinier explained. The only difference is that you will need to setup a redirect url for your app with specific url scheme like `yourapp://callback?access_token=12345`. Feel free to reopen the issue is you are not able to make it work.
